baseURL = 'https://yudetaro.com/'
locale = 'ja'
title = 'yudetaro.com'
theme = 'PaperMod'
[params]
  disableSpecial1stPost = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "blog"
  name = "ブログ"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "games"
  name = "自作ゲーム"
  url = "/games/"
  weight = 20
